// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RevloDB.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(RevloDbContext))]
    [Migration("20260321141759_AddBranchSoftDelete")]
    partial class AddBranchSoftDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RevloDB.Entities.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("KeyValue")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key_value");

                    b.Property<int>("NamespaceId")
                        .HasColumnType("integer")
                        .HasColumnName("namespace_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_api_keys_is_deleted_true")
                        .HasFilter("is_deleted = TRUE");

                    b.HasIndex("KeyValue")
                        .IsUnique()
                        .HasDatabaseName("ix_api_keys_key_value");

                    b.HasIndex("ExpiresAt", "IsDeleted")
                        .HasDatabaseName("ix_api_keys_expires_at_is_deleted")
                        .HasFilter("expires_at IS NOT NULL");

                    b.HasIndex("NamespaceId", "IsDeleted")
                        .HasDatabaseName("ix_api_keys_namespace_id_is_deleted");

                    b.HasIndex("UserId", "IsDeleted")
                        .HasDatabaseName("ix_api_keys_user_id_is_deleted");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("RevloDB.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("HeadCommitId")
                        .HasColumnType("integer")
                        .HasColumnName("head_commit_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("NamespaceId")
                        .HasColumnType("integer")
                        .HasColumnName("namespace_id");

                    b.HasKey("Id");

                    b.HasIndex("HeadCommitId")
                        .HasDatabaseName("ix_branches_head_commit_id");

                    b.HasIndex("NamespaceId")
                        .HasDatabaseName("ix_branches_namespace_id");

                    b.HasIndex("Name", "NamespaceId")
                        .IsUnique()
                        .HasDatabaseName("ix_branches_name_namespace_id");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("RevloDB.Entities.BranchState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer")
                        .HasColumnName("branch_id");

                    b.Property<string>("KeyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("key_name");

                    b.Property<int>("LastModifiedCommitId")
                        .HasColumnType("integer")
                        .HasColumnName("last_modified_commit_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_branch_states_branch_id");

                    b.HasIndex("BranchId", "KeyName")
                        .IsUnique()
                        .HasDatabaseName("ix_branch_states_branch_id_key_name");

                    b.ToTable("branch_states", (string)null);
                });

            modelBuilder.Entity("RevloDB.Entities.Commit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorUserId")
                        .HasColumnType("integer")
                        .HasColumnName("author_user_id");

                    b.Property<int>("Generation")
                        .HasColumnType("integer")
                        .HasColumnName("generation");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<int?>("MergeParentCommitId")
                        .HasColumnType("integer")
                        .HasColumnName("merge_parent_commit_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int>("NamespaceId")
                        .HasColumnType("integer")
                        .HasColumnName("namespace_id");

                    b.Property<int?>("ParentCommitId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_commit_id");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("MergeParentCommitId")
                        .HasDatabaseName("ix_commits_merge_parent_commit_id")
                        .HasFilter("merge_parent_commit_id IS NOT NULL");

                    b.HasIndex("NamespaceId")
                        .HasDatabaseName("ix_commits_namespace_id");

                    b.HasIndex("ParentCommitId")
                        .HasDatabaseName("ix_commits_parent_commit_id");

                    b.HasIndex("Hash", "NamespaceId")
                        .IsUnique()
                        .HasDatabaseName("ix_commits_hash_namespace_id");

                    b.HasIndex("NamespaceId", "Generation")
                        .HasDatabaseName("ix_commits_generation");

                    b.ToTable("commits", (string)null);
                });

            modelBuilder.Entity("RevloDB.Entities.CommitChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<int>("CommitId")
                        .HasColumnType("integer")
                        .HasColumnName("commit_id");

                    b.Property<string>("KeyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("key_name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("CommitId")
                        .HasDatabaseName("ix_commit_changes_commit_id");

                    b.HasIndex("CommitId", "KeyName")
                        .HasDatabaseName("ix_commit_changes_commit_id_key_name");

                    b.ToTable("commit_changes", (string)null);
                });

            modelBuilder.Entity("RevloDB.Entities.CommitSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommitId")
                        .HasColumnType("integer")
                        .HasColumnName("commit_id");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state_json");

                    b.HasKey("Id");

                    b.HasIndex("CommitId")
                        .IsUnique()
                        .HasDatabaseName("ix_commit_snapshots_commit_id");

                    b.ToTable("commit_snapshots", (string)null);
                });

            modelBuilder.Entity("RevloDB.Entities.Namespace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SnapshotInterval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("snapshot_interval");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_namespaces_created_by_user_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_namespace_is_deleted_true")
                        .HasFilter("is_deleted = TRUE");

                    b.HasIndex("Name", "CreatedByUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_namespaces_name_created_by_user_id")
                        .HasFilter("is_deleted = FALSE");

                    b.ToTable("namespaces", (string)null);
                });

            modelBuilder.Entity("RevloDB.Entities.UnstagedChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer")
                        .HasColumnName("branch_id");

                    b.Property<string>("KeyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("key_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_unstaged_changes_branch_id");

                    b.HasIndex("BranchId", "KeyName")
                        .IsUnique()
                        .HasDatabaseName("ix_unstaged_changes_branch_id_key_name");

                    b.ToTable("unstaged_changes", (string)null);
                });

            modelBuilder.Entity("RevloDB.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_salt");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_users_is_deleted_true")
                        .HasFilter("is_deleted = TRUE");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username")
                        .HasFilter("is_deleted = FALSE");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("RevloDB.Entities.UserNamespace", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("NamespaceId")
                        .HasColumnType("integer")
                        .HasColumnName("namespace_id");

                    b.Property<DateTime>("GrantedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("UserId", "NamespaceId");

                    b.HasIndex("NamespaceId")
                        .HasDatabaseName("ix_user_namespaces_namespace_id");

                    b.ToTable("user_namespaces", (string)null);
                });

            modelBuilder.Entity("RevloDB.Entities.ApiKey", b =>
                {
                    b.HasOne("RevloDB.Entities.Namespace", "Namespace")
                        .WithMany("ApiKeys")
                        .HasForeignKey("NamespaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_api_keys_namespaces_namespace_id");

                    b.HasOne("RevloDB.Entities.User", "User")
                        .WithMany("ApiKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_api_keys_users_user_id");

                    b.Navigation("Namespace");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RevloDB.Entities.Branch", b =>
                {
                    b.HasOne("RevloDB.Entities.Commit", "HeadCommit")
                        .WithMany()
                        .HasForeignKey("HeadCommitId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_branches_commits_head_commit_id");

                    b.HasOne("RevloDB.Entities.Namespace", "Namespace")
                        .WithMany("Branches")
                        .HasForeignKey("NamespaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_branches_namespaces_namespace_id");

                    b.Navigation("HeadCommit");

                    b.Navigation("Namespace");
                });

            modelBuilder.Entity("RevloDB.Entities.BranchState", b =>
                {
                    b.HasOne("RevloDB.Entities.Branch", "Branch")
                        .WithMany("BranchStates")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_branch_states_branches_branch_id");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("RevloDB.Entities.Commit", b =>
                {
                    b.HasOne("RevloDB.Entities.User", "AuthorUser")
                        .WithMany("AuthoredCommits")
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_commits_users_author_user_id");

                    b.HasOne("RevloDB.Entities.Commit", "MergeParentCommit")
                        .WithMany()
                        .HasForeignKey("MergeParentCommitId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_commits_commits_merge_parent_commit_id");

                    b.HasOne("RevloDB.Entities.Namespace", "Namespace")
                        .WithMany("Commits")
                        .HasForeignKey("NamespaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_commits_namespaces_namespace_id");

                    b.HasOne("RevloDB.Entities.Commit", "ParentCommit")
                        .WithMany()
                        .HasForeignKey("ParentCommitId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_commits_commits_parent_commit_id");

                    b.Navigation("AuthorUser");

                    b.Navigation("MergeParentCommit");

                    b.Navigation("Namespace");

                    b.Navigation("ParentCommit");
                });

            modelBuilder.Entity("RevloDB.Entities.CommitChange", b =>
                {
                    b.HasOne("RevloDB.Entities.Commit", "Commit")
                        .WithMany("Changes")
                        .HasForeignKey("CommitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_commit_changes_commits_commit_id");

                    b.Navigation("Commit");
                });

            modelBuilder.Entity("RevloDB.Entities.CommitSnapshot", b =>
                {
                    b.HasOne("RevloDB.Entities.Commit", "Commit")
                        .WithOne("Snapshot")
                        .HasForeignKey("RevloDB.Entities.CommitSnapshot", "CommitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_commit_snapshots_commits_commit_id");

                    b.Navigation("Commit");
                });

            modelBuilder.Entity("RevloDB.Entities.Namespace", b =>
                {
                    b.HasOne("RevloDB.Entities.User", "CreatedByUser")
                        .WithMany("CreatedNamespaces")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_namespaces_users_created_by_user_id");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("RevloDB.Entities.UnstagedChange", b =>
                {
                    b.HasOne("RevloDB.Entities.Branch", "Branch")
                        .WithMany("UnstagedChanges")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_unstaged_changes_branches_branch_id");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("RevloDB.Entities.UserNamespace", b =>
                {
                    b.HasOne("RevloDB.Entities.Namespace", "Namespace")
                        .WithMany("UserNamespaces")
                        .HasForeignKey("NamespaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_namespaces_namespaces_namespace_id");

                    b.HasOne("RevloDB.Entities.User", "User")
                        .WithMany("UserNamespaces")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_namespaces_users_user_id");

                    b.Navigation("Namespace");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RevloDB.Entities.Branch", b =>
                {
                    b.Navigation("BranchStates");

                    b.Navigation("UnstagedChanges");
                });

            modelBuilder.Entity("RevloDB.Entities.Commit", b =>
                {
                    b.Navigation("Changes");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("RevloDB.Entities.Namespace", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("Branches");

                    b.Navigation("Commits");

                    b.Navigation("UserNamespaces");
                });

            modelBuilder.Entity("RevloDB.Entities.User", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("AuthoredCommits");

                    b.Navigation("CreatedNamespaces");

                    b.Navigation("UserNamespaces");
                });
#pragma warning restore 612, 618
        }
    }
}
